In [15]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_excel(r"F:\python\Data Analysis Projects\Sports Dataset\1 - 2019 ODI Cricket Matches.xlsx")
df

,Team 1,Team 2,Winner,Margin,Ground,Match Date,Scorecard
0,New Zealand,Pakistan,New Zealand,61 runs,Wellington,2018-01-06,ODI # 3946
1,New Zealand,Pakistan,New Zealand,8 wickets,Nelson,2018-01-09,ODI # 3947
2,U.A.E.,Ireland,Ireland,4 wickets,ICCA Dubai,2018-01-11,ODI # 3948
3,New Zealand,Pakistan,New Zealand,183 runs,Dunedin,2018-01-13,ODI # 3949
4,U.A.E.,Ireland,Ireland,67 runs,ICCA Dubai,2018-01-13,ODI # 3950
...,...,...,...,...,...,...,...
123,Australia,South Africa,South Africa,40 runs,Hobart,2018-11-11,ODI # 4069
124,New Zealand,Pakistan,no result,NaN,Dubai (DSC),2018-11-11,ODI # 4070
125,Bangladesh,West Indies,Bangladesh,5 wickets,Dhaka,2018-12-09,ODI # 4071
126,Bangladesh,West Indies,West Indies,4 wickets,Dhaka,2018-12-11,ODI # 4072
127,Bangladesh,West Indies,Bangladesh,8 wickets,Sylhet,2018-12-14,ODI # 4073

Task 1: Transform the 'margin' column into two, one for wickets and other for runs!

In [19]:
import re
file = df['Margin']
resultt =re.match("(r\w+)",file)
df.insert(5,"Win by Runs", resultt  )

TypeError: expected string or bytes-like object